stages:
  - deploy

default:
  image: node:22
  before_script:
    - npm install --global vercel

deploy_preview:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      changes:
        - frontend/**/*
  script:
    - cd frontend
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - frontend/**/*
  script:
    - cd frontend
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
