CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    uuid VARCHAR(255) NOT NULL UNIQUE,
    point Integer   NOT NULL default 0,
    profile_image   TEXT    NULL,
    created_at TIMESTAMP(6) NOT NULL Default CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)
);

-- 리프레시 토큰은 기기(세션)당 한 행이다. uuid 에 UNIQUE 를 걸면 사용자당 토큰이 하나로
-- 묶여 PC 에서 로그인하면 모바일 세션이 끊긴다. 그래서 UNIQUE 는 device_id 에만 있다.
CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 사용자 식별자(users.uuid). 한 사용자가 여러 기기를 가지므로 중복될 수 있다.
    uuid VARCHAR(255) NOT NULL,
    -- 기기 식별자. 로그인할 때마다 서버가 새로 발급하고 리프레시 토큰 클레임에 넣는다.
    device_id VARCHAR(64) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refresh_token_device UNIQUE (device_id)
);

-- 한 사용자의 세션 전체를 훑는 일이 잦다(로그아웃, 재사용 탐지 시 전체 폐기).
CREATE INDEX idx_refresh_token_uuid ON refresh_token (uuid);

-- findByToken 이 전체 스캔으로 돌지 않도록.
CREATE INDEX idx_refresh_token_token ON refresh_token (token);

CREATE TABLE oauth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_oauth_identities_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_oauth_identities_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_oauth_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_oauth_identities_provider CHECK (provider IN ('KAKAO'))
);

CREATE INDEX idx_oauth_identities_user ON oauth_identities (user_id);
