-- 건물 카탈로그와 유저 인벤토리.

CREATE TABLE building_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_key VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    theme VARCHAR(30) NOT NULL,
    type VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL DEFAULT 0,
    default_granted BOOLEAN NOT NULL DEFAULT FALSE,
    size_width NUMERIC(6, 3) NOT NULL,
    size_depth NUMERIC(6, 3) NOT NULL,
    size_height NUMERIC(6, 3) NOT NULL,
    parts JSONB NOT NULL,
    thumbnail_url TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_building_item_type CHECK (type IN ('NORMAL', 'LANDMARK')),
    CONSTRAINT ck_building_item_price CHECK (price >= 0)
);

CREATE INDEX idx_building_item_theme ON building_item (theme);
CREATE INDEX idx_building_item_type ON building_item (type);
CREATE INDEX idx_building_item_sort ON building_item (sort_order);

CREATE TABLE user_building (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    building_item_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_building UNIQUE (user_id, building_item_id),
    CONSTRAINT fk_user_building_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_building_item FOREIGN KEY (building_item_id) REFERENCES building_item (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_building_user ON user_building (user_id);
