-- 만다라트 시트 · 세부목표(domain) · 하위과제(subject) · 좋아요 스키마.

-- 만다라트 시트
CREATE TABLE sheet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    is_open BOOLEAN NOT NULL DEFAULT FALSE,
    like_count BIGINT DEFAULT 0,
    expired_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sheet_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_sheet_like_count CHECK (like_count >= 0)
);

CREATE INDEX idx_sheet_user ON sheet (user_id);

-- 세부목표 (시트의 9개 구역)
CREATE TABLE domain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sheet_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,
    subject_count INTEGER,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_domain_sheet FOREIGN KEY (sheet_id)
        REFERENCES sheet (id) ON DELETE CASCADE
);

CREATE INDEX idx_domain_sheet ON domain (sheet_id);

-- 하위과제
CREATE TABLE subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    point BIGINT NOT NULL DEFAULT 0,
    target_count INTEGER,
    try_count INTEGER DEFAULT 0,
    position INTEGER NOT NULL,
    is_done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT (CURRENT_TIMESTAMP - INTERVAL '1 day'),
    CONSTRAINT fk_subject_domain FOREIGN KEY (domain_id)
        REFERENCES domain (id) ON DELETE CASCADE,
    CONSTRAINT fk_subject_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_subject_period_type CHECK (period_type IN ('DAILY', 'WEEKLY', 'NONE'))
);

CREATE INDEX idx_subject_domain ON subject (domain_id);
CREATE INDEX idx_subject_user ON subject (user_id);

-- 좋아요 기록 (LikesId 복합키)
CREATE TABLE likes (
    user_id BIGINT NOT NULL,
    sheet_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT likes_pkey PRIMARY KEY (user_id, sheet_id),
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_sheet FOREIGN KEY (sheet_id)
        REFERENCES sheet (id) ON DELETE CASCADE
);

CREATE INDEX idx_likes_sheet ON likes (sheet_id);
