-- ============================================================
-- 친구 요청 (request) 및 친구 관계 (friends) 스키마 정의
-- ============================================================

-- 친구 요청 테이블
CREATE TABLE request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    progress VARCHAR(20) NOT NULL DEFAULT 'NOT_READ',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_request_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_request_progress CHECK (
        progress IN (
            'ACCEPTED',
            'REJECTED',
            'READ',
            'NOT_READ'
        )
    ),
    CONSTRAINT uk_request_pair UNIQUE (sender_id, receiver_id)
);
-- 친구 관계 테이블
CREATE TABLE friends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id1 BIGINT NOT NULL,
    user_id2 BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_friends_user1 FOREIGN KEY (user_id1) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friends_user2 FOREIGN KEY (user_id2) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_friends_pair UNIQUE (user_id1, user_id2)
);

CREATE INDEX idx_friends_user1 ON friends (user_id1);

CREATE INDEX idx_friends_user2 ON friends (user_id2);
