-- 건물 배치 정보.
--
-- 시트 한 장은 9개 구역(domain_position 1~9) × 9개 타일(item_position 1~9) 격자를 갖고,
-- 각 타일에 어떤 건물 스킨을 어느 방향으로 놓았는지를 이 테이블이 담는다.
-- 중앙 구역(5)은 3×3 랜드마크 한 칸으로 쓰므로 시트당 1 + 8×9 = 73 행이 생성된다.
--
-- sheet 를 참조하므로 sheet 테이블을 만드는 마이그레이션(V6)보다 뒤에 와야 한다.
--
-- ERD 의 item_spot 에는 type / domain_id / subject_id 가 더 있으나 ItemSpot 엔티티가
-- 매핑하지 않아 넣지 않았다. 위치는 domain_position + item_position 으로 이미 표현된다.
-- 필요해지면 nullable 컬럼 추가(ALTER TABLE ADD COLUMN)로 붙일 수 있다.

CREATE TABLE item_spot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sheet_id BIGINT NOT NULL,

    -- 보유 건물(user_building.id). NULL 은 "기본 스킨" 을 뜻한다 —
    -- 유저가 스킨을 지정하지 않은 타일에 SheetService 가 null 을 넣는다.
    inven_id BIGINT,

    domain_position INTEGER NOT NULL,
    item_position INTEGER NOT NULL,

    -- ItemDir 이 @Enumerated(EnumType.STRING) 이라 상수 이름이 그대로 저장된다.
    -- ERD 표기는 '0'/'90'/'180'/'270' 이지만 실제 저장값은 DEG_0/DEG_90/... 이다.
    -- ItemDir 의 @JsonValue 는 JSON 직렬화에만 적용되고 DB 에는 영향이 없다.
    dir VARCHAR(10) NOT NULL DEFAULT 'DEG_0',

    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_item_spot_sheet FOREIGN KEY (sheet_id)
        REFERENCES sheet (id) ON DELETE CASCADE,

    -- 건물을 처분해도 배치 칸은 남고 기본 스킨으로 돌아간다.
    -- CASCADE 로 두면 배치 칸이 사라져 만다라트 격자에 구멍이 생긴다.
    CONSTRAINT fk_item_spot_inven FOREIGN KEY (inven_id)
        REFERENCES user_building (id) ON DELETE SET NULL,

    -- 같은 타일에 두 건물이 놓이는 것을 DB 에서 막는다.
    CONSTRAINT uk_item_spot_tile UNIQUE (sheet_id, domain_position, item_position),

    CONSTRAINT ck_item_spot_domain_position CHECK (domain_position BETWEEN 1 AND 9),
    CONSTRAINT ck_item_spot_item_position CHECK (item_position BETWEEN 1 AND 9),
    CONSTRAINT ck_item_spot_dir CHECK (dir IN ('DEG_0', 'DEG_90', 'DEG_180', 'DEG_270'))
);

-- findBySheetId 는 uk_item_spot_tile 의 선두 컬럼(sheet_id)으로 커버되므로
-- sheet_id 단독 인덱스를 따로 만들지 않는다.
-- inven_id 는 건물 처분 시 어느 칸이 그 건물을 쓰는지 역방향으로 찾는 데 쓴다.
CREATE INDEX idx_item_spot_inven ON item_spot (inven_id);
