-- 과제 수행 이력 (Subject Log)
CREATE TABLE subject_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    earned_point BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subject_log_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_subject_log_subject FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE
);

CREATE INDEX idx_subject_log_user ON subject_log (user_id);
CREATE INDEX idx_subject_log_subject ON subject_log (subject_id);
