-- ============================================================
-- 그룹 만다라트 스키마 정의 (group_sheet, groups, group_request)
-- ============================================================

-- 그룹 공용 시트: 멤버 4명이 각 2개씩 기여한 도메인 참조 (총 8슬롯)
CREATE TABLE group_sheet (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id1   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id2   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id3   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id4   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id5   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id6   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id7   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    domain_id8   BIGINT REFERENCES domain(id) ON DELETE SET NULL,
    created_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 그룹: 팀장(creator) + 팀원 최대 3명
CREATE TABLE groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    creator_id      BIGINT NOT NULL REFERENCES users(id),
    group_sheet_id  BIGINT REFERENCES group_sheet(id),
    user_id1        BIGINT REFERENCES users(id),  -- 팀원1
    user_id2        BIGINT REFERENCES users(id),  -- 팀원2
    user_id3        BIGINT REFERENCES users(id),  -- 팀원3
    inven_id        BIGINT,                        -- 중앙 랜드마크 건물
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 그룹 초대 요청
CREATE TABLE group_request (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    creator_id  BIGINT NOT NULL REFERENCES users(id),  -- 초대 보낸 팀장
    receiver_id BIGINT NOT NULL REFERENCES users(id),  -- 초대 받은 팀원
    progress    VARCHAR(20) NOT NULL DEFAULT 'NOT_READ',
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_group_request_progress CHECK (progress IN ('NOT_READ', 'READ', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT uk_group_request UNIQUE (group_id, receiver_id)
);

CREATE INDEX idx_groups_creator ON groups (creator_id);
CREATE INDEX idx_groups_user1 ON groups (user_id1);
CREATE INDEX idx_groups_user2 ON groups (user_id2);
CREATE INDEX idx_groups_user3 ON groups (user_id3);
CREATE INDEX idx_group_request_receiver ON group_request (receiver_id);
