-- 만다라트 진행률 마일스톤 보상 수령 기록.
--
-- 진행률 12.5% 구간(1~8)마다 크레딧 또는 랜드마크를 준다. **계정당 구간별 1회**이므로
-- 시트를 새로 만들어도 다시 받을 수 없다 — 그래서 sheet_id 를 갖지 않는다. 어느 시트로
-- 도달했는지는 보상의 성립 조건이 아니라 경위일 뿐이고, 그걸 키에 넣으면 시트마다 한 번씩
-- 받게 된다.
--
-- UNIQUE (user_id, milestone) 이 "1회" 의 실질이다. 애플리케이션 검사만으로 두면 더블클릭이나
-- 동시 요청에 두 번 지급된다 — 받는 것이 포인트와 건물이라 되돌리기가 번거롭다. DB 가 막는다.

CREATE TABLE reward_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    -- 구간 번호 1~8. 퍼센트(12.5 배수)를 그대로 담지 않는 이유는 소수점 비교를 피하려는 것이다.
    milestone SMALLINT NOT NULL,
    kind VARCHAR(16) NOT NULL,
    -- 지급 결과. 무엇을 받았는지 화면에 다시 보여주고, 문제가 생겼을 때 추적하려고 남긴다.
    granted_point INTEGER,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reward_claim UNIQUE (user_id, milestone),
    CONSTRAINT ck_reward_claim_milestone CHECK (milestone BETWEEN 1 AND 8),
    CONSTRAINT ck_reward_claim_kind CHECK (kind IN ('CREDIT', 'LANDMARK')),
    CONSTRAINT fk_reward_claim_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_reward_claim_user ON reward_claim (user_id);

-- 한 번 수령으로 랜드마크 여러 종이 나올 수 있다(100% 구간은 남은 전종을 준다).
-- 그래서 지급된 건물은 1:N 으로 따로 담는다.
CREATE TABLE reward_claim_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_claim_id BIGINT NOT NULL,
    building_item_id BIGINT NOT NULL,
    CONSTRAINT fk_reward_claim_item_claim FOREIGN KEY (reward_claim_id)
        REFERENCES reward_claim (id) ON DELETE CASCADE,
    CONSTRAINT fk_reward_claim_item_building FOREIGN KEY (building_item_id)
        REFERENCES building_item (id) ON DELETE CASCADE
);

CREATE INDEX idx_reward_claim_item_claim ON reward_claim_item (reward_claim_id);
